refactor to improve performance and accessibility
smartcontentor/todo-app pull request #1
Opened 2022-06-18 12:56 UTC by smartcontentor

2022-06-20 09:41 UTC, MahdiMajdian approved these changes

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.css
> +  --regular-shadow:rgba(149, 157, 165, 0.2) 0px 8px 24px;
```suggestion
  --regular-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;
```
won't prettier handle this?

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.css
> +  margin:0;
```suggestion
  margin: 0;
```

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.css
> +  width: 80vw;
still using vw unit

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.css
> +  width: 80vw;
same

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.css
> +  font-size: 1.2rem;
change it px

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.js
> +  );
separate callbacks with an empty line, do this for all of callbacks in this file

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.js
> +    []
add missing dependencies

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.js
> +  }, []);
missing dependencies

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.js
> +  const handleNewTodoText = useCallback((e) => {
```suggestion
  const handleNewTodoText = useCallback((event) => {
```
always avoid abbreviations

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.js
> +  }, []);
missing dependencies

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.js
> +    setNewTodoText(() => e.target.value);
why did you used a callback inside setNewTodoText?

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.js
> +  const handleNewTodo = useCallback((e) => {
handleNewTodo is a vague name, 
handleAddNewTodo provide context about what it dose

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.js
> +      if (newTodoText) {
check specifically if it's not empty

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.js
> +      setNewTodoText(() => "");
```suggestion
      setNewTodoText('');
```

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.js
> +    [newTodoText]
missing dependencies

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.js
> +            onClick={handleNewTodo}
I think we are using form to handle button submit with accessibility so adding onClick is a redundant since form is handling that for us.

2022-06-20 09:41 UTC, MahdiMajdian commented on src/App.js
> +          onChangeStatus={handleChangeStatus}
give this data and way to change data as we discussed.

2022-06-20 09:41 UTC, MahdiMajdian commented on src/Todo.css
>    width: 80vw;
change unit

2022-06-20 09:41 UTC, MahdiMajdian commented on src/Todo.css
> +  transform: scale(1.2);
I don't understand why we used transform here?

2022-06-20 09:41 UTC, MahdiMajdian commented on src/Todo.css
> +}
add new empty line at the end of every file

2022-06-20 09:41 UTC, MahdiMajdian commented on src/Todo.css
> +  accent-color: var(--primary-color);
accent color change the style of our checkbox and should be given to  `.todo-checkbox` selector
css will handle different states of this checkbox.
move it to the mentioned selector if you agree with my reasoning.

2022-06-20 09:41 UTC, MahdiMajdian commented on src/Todo.js
>        ></i>
make this element self closing since it has no content

2022-06-20 09:41 UTC, MahdiMajdian commented on src/TodoList.css
> +}
new line

2022-06-20 09:41 UTC, MahdiMajdian commented on src/TodoList.js
>  function TodoList({ todos, onDeleteTodo, onChangeStatus }) {
change this as we discussed to handle callback inside it self

2022-06-20 09:41 UTC, MahdiMajdian commented on src/index.css
> +}
new line

2022-06-20 10:21 UTC, MahdiMajdian commented on src/App.css
> +  margin: 30px auto;
Use `inline-start/end` and `block-start/end` keywords words for `margin/padding` instead of `top/right/bottom/left`.

2022-06-20 10:21 UTC, MahdiMajdian commented on src/App.css
> +  margin: 20px 0;
Use `inline-start/end` and `block-start/end` keywords words for `margin/padding` instead of `top/right/bottom/left`.

2022-06-20 10:21 UTC, MahdiMajdian commented on src/App.css
> +  padding: 10px 18px;
Use `inline-start/end` and `block-start/end` keywords words for `margin/padding` instead of `top/right/bottom/left`.

2022-06-20 10:21 UTC, MahdiMajdian commented on src/Todo.css
>    padding: 25px 30px;
Use `inline-start/end` and `block-start/end` keywords words for `margin/padding` instead of `top/right/bottom/left`.

2022-06-20 10:22 UTC, MahdiMajdian commented on src/Todo.css
>    margin: 25px 0;
Use `inline-start/end` and `block-start/end` keywords words for `margin/padding` instead of `top/right/bottom/left`.

2022-06-20 10:22 UTC, MahdiMajdian commented on src/Todo.css
> +  margin-left: 7px;
Use `inline-start/end` and `block-start/end` keywords words for `margin/padding` instead of `top/right/bottom/left`.

2022-06-20 10:28 UTC, smartcontentor commented on src/App.js
> +  );
like this??

`  const handleNewTodoText = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      setNewTodoText(() => e.target.value);
    },
    [setNewTodoText]
  );`

2022-06-20 10:30 UTC, MahdiMajdian requested changes
we have decided to use conventional commits from now on, please read this and change your commit messages accordingly, read more _[here](https://www.conventionalcommits.org/en/v1.0.0/)_

2022-06-20 10:35 UTC, smartcontentor commented on src/App.js
> +      if (newTodoText) {
like this?
`if (newTodoText.trim().length !== 0)`

2022-06-20 10:39 UTC, smartcontentor commented on src/App.js
> +            onClick={handleNewTodo}
we found this issue in typescript, did you remember?😉

2022-06-22 14:43 UTC, MahdiMajdian commented
No changes were made to resolve conversations.
pay attention to this in the future

2022-06-22 14:43 UTC, closed without merging

2022-06-22 14:50 UTC, MahdiMajdian commented on src/App.js
> +  );
not fixed

2022-06-22 14:52 UTC, MahdiMajdian commented on src/App.js
> +  }, []);
not fixed

2022-06-22 14:57 UTC, MahdiMajdian commented on src/App.js
> +    [newTodoText]
not fixed